<?php

namespace Saloon\Traits\OAuth2;

use DateInterval;
use DateTimeImmutable;
use Exception;
use Saloon\Exceptions\OAuthConfigValidationException;
use Saloon\Exceptions\PendingRequestException;
use Saloon\Exceptions\Request\FatalRequestException;
use Saloon\Exceptions\Request\RequestException;
use Saloon\Http\Request;
use Saloon\Http\Response;
use InvalidArgumentException;
use Saloon\Helpers\URLHelper;
use Saloon\Helpers\StringHelpers;
use Saloon\Helpers\OAuth2\OAuthConfig;
use Saloon\Http\OAuth2\GetUserRequest;
use Saloon\Contracts\OAuthAuthenticator;
use Saloon\Exceptions\InvalidStateException;
use Saloon\Http\OAuth2\GetAccessTokenRequest;
use Saloon\Http\Auth\AccessTokenAuthenticator;
use Saloon\Http\OAuth2\GetRefreshTokenRequest;

trait AuthorizationCodeGrant
{
    use HasOAuthConfig;

    /**
     * The state generated by the getAuthorizationUrl method.
     *
     * @var string|null
     */
    protected $state = null;

    /**
     * Get the Authorization URL.
     *
     * @param array<string> $scopes
     * @param string|null $state
     * @param string $scopeSeparator
     * @param array<string, string> $additionalQueryParameters
     *
     * @return string
     *
     * @throws OAuthConfigValidationException
     * @throws Exception
     */
    public function getAuthorizationUrl(array $scopes = [], $state = null, $scopeSeparator = ' ', array $additionalQueryParameters = [])
    {
        $config = $this->oauthConfig();

        $config->validate();

        $clientId = $config->getClientId();
        $redirectUri = $config->getRedirectUri();
        $defaultScopes = $config->getDefaultScopes();

        $this->state = isset($state) ? $state : StringHelpers::random(32);

        $queryParameters = array_filter(array_merge([
            'response_type' => 'code',
            'scope' => implode(
                $scopeSeparator,
                array_filter(array_merge($defaultScopes, $scopes))
            ),
            'client_id' => $clientId,
            'redirect_uri' => $redirectUri,
            'state' => $this->state,
        ], $additionalQueryParameters));

        $query = http_build_query($queryParameters, '', '&', PHP_QUERY_RFC3986);
        $query = trim($query, '?&');

        $url = URLHelper::join($this->resolveBaseUrl(), $config->getAuthorizeEndpoint());

        $glue = strpos($url, '?') !== false ? '&' : '?';

        return $url . $glue . $query;
    }

    /**
     * Get the access token.
     *
     * @template TRequest of Request
     *
     * @param string $code
     * @param ?string $state
     * @param ?string $expectedState
     * @param bool $returnResponse
     * @param callable(TRequest): (void)|null $requestModifier
     *
     * @return OAuthAuthenticator|Response
     *
     * @throws InvalidStateException
     * @throws OAuthConfigValidationException
     * @throws FatalRequestException
     * @throws RequestException
     * @throws PendingRequestException
     * @throws Exception
     */
    public function getAccessToken($code, $state = null, $expectedState = null, $returnResponse = false, callable $requestModifier = null)
    {
        $this->oauthConfig()->validate();

        if (! empty($state) && ! empty($expectedState) && $state !== $expectedState) {
            throw new InvalidStateException();
        }

        $request = $this->resolveAccessTokenRequest($code, $this->oauthConfig());

        $request = $this->oauthConfig()->invokeRequestModifier($request);

        if (is_callable($requestModifier)) {
            $requestModifier($request);
        }

        $response = $this->send($request);

        if ($returnResponse === true) {
            return $response;
        }

        $response->throwException();

        return $this->createOAuthAuthenticatorFromResponse($response);
    }

    /**
     * Refresh the access token.
     *
     * @template TRequest of Request
     *
     * @param OAuthAuthenticator|string $refreshToken
     * @param bool $returnResponse
     * @param callable(TRequest): (void)|null $requestModifier
     *
     * @return OAuthAuthenticator|Response
     * @throws FatalRequestException
     * @throws OAuthConfigValidationException
     * @throws RequestException
     * @throws PendingRequestException
     * @throws Exception
     */
    public function refreshAccessToken($refreshToken, $returnResponse = false, callable $requestModifier = null)
    {
        $this->oauthConfig()->validate();

        if ($refreshToken instanceof OAuthAuthenticator) {
            if ($refreshToken->isNotRefreshable()) {
                throw new InvalidArgumentException('The provided OAuthAuthenticator does not contain a refresh token.');
            }

            $refreshToken = $refreshToken->getRefreshToken();
        }

        $request = $this->resolveRefreshTokenRequest($this->oauthConfig(), $refreshToken);

        $request = $this->oauthConfig()->invokeRequestModifier($request);

        if (is_callable($requestModifier)) {
            $requestModifier($request);
        }

        $response = $this->send($request);

        if ($returnResponse === true) {
            return $response;
        }

        $response->throwException();

        return $this->createOAuthAuthenticatorFromResponse($response, $refreshToken);
    }

    /**
     * Create the OAuthAuthenticator from a response.
     *
     * @param string|null $fallbackRefreshToken
     *
     * @return OAuthAuthenticator
     *
     * @throws Exception
     */
    protected function createOAuthAuthenticatorFromResponse(Response $response, $fallbackRefreshToken = null)
    {
        $responseData = $response->object();

        $accessToken = $responseData->access_token;
        $refreshToken = isset($responseData->refresh_token) ? $responseData->refresh_token : $fallbackRefreshToken;

        $expiresAt = null;

        if (isset($responseData->expires_in) && is_numeric($responseData->expires_in)) {
            $expiresAt = (new DateTimeImmutable)->add(
                DateInterval::createFromDateString((int)$responseData->expires_in . ' seconds')
            );
        }

        return $this->createOAuthAuthenticator($accessToken, $refreshToken, $expiresAt);
    }

    /**
     * Create the authenticator.
     *
     * @param string $accessToken
     * @param ?string $refreshToken
     *
     * @return OAuthAuthenticator
     */
    protected function createOAuthAuthenticator($accessToken, $refreshToken = null, DateTimeImmutable $expiresAt = null)
    {
        return new AccessTokenAuthenticator($accessToken, $refreshToken, $expiresAt);
    }

    /**
     * Get the authenticated user.
     *
     * @template TRequest of Request
     *
     * @param OAuthAuthenticator $oauthAuthenticator
     * @param callable(TRequest): (void)|null $requestModifier
     *
     * @return Response
     *
     * @throws FatalRequestException
     * @throws RequestException
     * @throws PendingRequestException
     */
    public function getUser(OAuthAuthenticator $oauthAuthenticator, callable $requestModifier = null)
    {
        $request = $this->resolveUserRequest($this->oauthConfig())->authenticate($oauthAuthenticator);

        if (is_callable($requestModifier)) {
            $requestModifier($request);
        }

        $request = $this->oauthConfig()->invokeRequestModifier($request);

        return $this->send($request);
    }

    /**
     * Get the state that was generated in the getAuthorizationUrl() method.
     *
     * @return ?string
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Resolve the access token request
     *
     * @param string $code
     *
     * @return Request
     */
    protected function resolveAccessTokenRequest($code, OAuthConfig $oauthConfig)
    {
        return new GetAccessTokenRequest($code, $oauthConfig);
    }

    /**
     * Resolve the refresh token request
     *
     * @param string $refreshToken
     *
     * @return Request
     */
    protected function resolveRefreshTokenRequest(OAuthConfig $oauthConfig, $refreshToken)
    {
        return new GetRefreshTokenRequest($oauthConfig, $refreshToken);
    }

    /**
     * Resolve the user request
     *
     * @return Request
     */
    protected function resolveUserRequest(OAuthConfig $oauthConfig)
    {
        return new GetUserRequest($oauthConfig);
    }
}
